### ISSUE TITLE
Sorry for contacting you here

### ISSUE THREAD

**Issue by PASAf** [andreesteve/stresspoint#1]
Hello,
I'm sorry to posting this message to you as issue for your repository, but I didn't found other way to contact you.

This is your blog https://designprincipia.com/virtualize-uefi-on-arm-using-qemu/ isn't it? I'm trying to follow your steps, but didn't found this file: http://bep.si/?nge3y website seems to be down. Could you reupload it somewhere, please?

**Comment by PASAf** [comment]
Nevermind, downloaded it. How its going with rootfs by the way?

**Comment by andreesteve** [comment]
I guess I need a comment section on the blog :)
I checked the links on that page, all seem fine. Let me know if you still see any misbehaving and I'll update them.
